"""empty message

Revision ID: 17d46a57adac
Revises: 
Create Date: 2023-10-21 13:58:13.058486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d46a57adac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('years_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['years_id'], ['years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month'], ['month.id'], ),
    sa.ForeignKeyConstraint(['year'], ['years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['days'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_lessons')
    op.drop_table('days')
    op.drop_table('month')
    op.drop_table('years')
    # ### end Alembic commands ###
